os: Visual Studio 2017

build_script:
  - cmd: build.cmd BuildApp
  - cmd: build.cmd RunTests
  - cmd: build.cmd CreatePackages

test: off

nuget:
  project_feed: true

artifacts:
  - path: 'packaging\**\scientist*.nupkg'
    name: ScientistPackages

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true